### ISSUE TITLE
Colored shapes for API methods and API responses

### ISSUE THREAD

**Issue by bdw429s** [scottsteinbeck/commandbox-gitbook#10]

**Comment by bdw429s** [comment]
![image](https://user-images.githubusercontent.com/584009/62582733-08ce5300-b873-11e9-8e44-f1193457bb84.png)

![image](https://user-images.githubusercontent.com/584009/62582739-0d930700-b873-11e9-9c21-e04538fff18c.png)

**Comment by scottsteinbeck** [comment]
added in styles for these blocks
