### ISSUE TITLE
Tone down colors on inline code 

### ISSUE THREAD

**Issue by bdw429s** [scottsteinbeck/commandbox-gitbook#14]
Here is an excerpt from a page on the CommandBox Gitbook as rendered by Gitbook.com

![image](https://user-images.githubusercontent.com/584009/62582810-4cc15800-b873-11e9-80e2-ae1da7eed03f.png)

And here is our version

![image](https://user-images.githubusercontent.com/584009/62582803-48953a80-b873-11e9-88ed-338fd30fd6a8.png)

The red code snippets stand out a bit too much I think

**Comment by scottsteinbeck** [comment]
Colors have been changed to match the Gitbook styles
