### ISSUE TITLE
table widths don't seem correct sometimes

### ISSUE THREAD

**Issue by bdw429s** [scottsteinbeck/commandbox-gitbook#16]
Here's a screenshot of the moden-CFML book.  I'm not sure how the table is defined, but the first column is super wide even though there is not much text on any row.  The right column has tons of text, but is really small.

![image](https://user-images.githubusercontent.com/584009/62808317-5b9b4b00-babd-11e9-9735-840e9fc4275a.png)

**Comment by scottsteinbeck** [comment]
fixed.
