### ISSUE TITLE
Paragraphs not respected

### ISSUE THREAD

**Issue by lmajano** [scottsteinbeck/commandbox-gitbook#18]
The paragraphs are not respected in the output. See original and export images.
<img width="824" alt="original" src="https://user-images.githubusercontent.com/137111/62809374-60153300-bac0-11e9-9255-024d97d5eaac.png">
![export](https://user-images.githubusercontent.com/137111/62809375-60153300-bac0-11e9-9a84-7bfb677cbacc.png)

**Comment by scottsteinbeck** [comment]
now they are respected.
