### ISSUE TITLE
Gitbook link blocks are ignored

### ISSUE THREAD

**Issue by lmajano** [scottsteinbeck/commandbox-gitbook#20]
All gitbook link blocks are ignored in output.  Would be nice to do something similar 
![Screen Shot 2019-08-09 at 4 17 48 PM](https://user-images.githubusercontent.com/137111/62809684-4a543d80-bac1-11e9-9be8-0b13fa9ef0e5.png)

**Comment by lmajano** [comment]
Also make sure they are hyperlinked from the PDF

**Comment by bdw429s** [comment]
@scottsteinbeck This example pictured here is on the asyncronous programming page

**Comment by bdw429s** [comment]
It looks like these are a block type of embed and have an empty child node that outputs nothing.  The embed object has `node.data.url` which is the actual thing being embedded.  The title of the page isn't included in the JSON so it appears that Gitbook fetches the URL and looks at the title of the page and then builds the little box out of it.

I assume there are different kind of "embed" types, but I'm not sure what they are.

**Comment by bdw429s** [comment]
I've added a method in book service that takes a URL, and gets
* the raw host name from it
* hits it with a GET, parses the HTML, and grabs the page title with an XPath search

The data is being output now with the link, it just needs styled.

**Comment by scottsteinbeck** [comment]
Styled, and added metadata for the website description is there is one, also added a pull for the favicon logo, but didn't implement it yet.
