### ISSUE TITLE
Hyperlinked text is not hyperlinked in the PDF

### ISSUE THREAD

**Issue by lmajano** [scottsteinbeck/commandbox-gitbook#21]
Hyperlinked text is not hyperlinked in the PDF. see screenshots
![export](https://user-images.githubusercontent.com/137111/62809869-cea6c080-bac1-11e9-91a2-4d27eae6c3ed.png)
![original](https://user-images.githubusercontent.com/137111/62809870-cea6c080-bac1-11e9-83b1-e6f3df0b8eff.png)

**Comment by scottsteinbeck** [comment]
Resolved, links are now hyperlinked
