### ISSUE TITLE
Only show image once per alert box

### ISSUE THREAD

**Issue by bdw429s** [scottsteinbeck/commandbox-gitbook#23]
This ex is from the ORM chapter in modern CFML.  

![image](https://user-images.githubusercontent.com/584009/62817988-b35da480-bb05-11e9-95e0-ff82e30b5421.png)

**Comment by bdw429s** [comment]
Also note that our text is wrapping under the image.  Keep the text away

**Comment by scottsteinbeck** [comment]
fixed.
