### ISSUE TITLE
Key [Document] doesn't exist error

### ISSUE THREAD

**Issue by computergeek1507** [scottsteinbeck/commandbox-gitbook#33]
Get the following error when I try to export my gitbook project. Using 
JRE 1.8.0_171
![image](https://user-images.githubusercontent.com/2293065/66879717-6a0a5500-ef8d-11e9-9468-5e27d787e4a7.png)

**Comment by bdw429s** [comment]
Thanks for the report @computergeek1507 can you provide a copy of your Gitbook export for me to try this on?  I'm guessing it's related to the data in your export being different than our tests.

**Comment by computergeek1507** [comment]
https://drive.google.com/file/d/1FO9QAdClkevvNo1o69bxRdr_eT94eSH4/view?usp=sharing

**Comment by bdw429s** [comment]
@computergeek1507 Thanks, I'll give this a test.  Sorry for the delays in replying, I've been in Germany in a conference so not on my normal timezone.

**Comment by bdw429s** [comment]
@computergeek1507 Very interesting, the export seems to be a bit corrupted.  The contents of the file
```
gitbook_xLights\versions\master\layout-and-background-image-definition.json
```
is this:
```js
{"error":{"code":503,"message":"Service Unavailable. Could not get object","status":"GET_OBJECT"}}
```
I'll just put in some more error checking for now, but I would recommend re-downloading your exported book.

**Comment by computergeek1507** [comment]
Thanks, I will try that

**Comment by bdw429s** [comment]
@computergeek1507 I also found an issue with CMKY images as well that I put in a check for.   You can grab the latest version of the command by running
```update --system```

**Comment by computergeek1507** [comment]
I get this error on box startup after updating gitbook-exporter
![image](https://user-images.githubusercontent.com/2293065/67134010-9ddbb980-f1dd-11e9-8fdf-ecc2dbe6c142.png)

**Comment by computergeek1507** [comment]
I got it to export but the PDF is missing images with this "[ inline-image ]" red line error
![image](https://user-images.githubusercontent.com/2293065/67134782-104e9880-f1e2-11e9-9515-65a190f4aa71.png)

**Comment by computergeek1507** [comment]
this error too
![image](https://user-images.githubusercontent.com/2293065/67135048-b77fff80-f1e3-11e9-906f-fd6a62845aed.png)

**Comment by computergeek1507** [comment]
https://drive.google.com/file/d/1Yx4Pn2qTJEhuPymtLp8ZKat3IN2XFjRa/view?usp=sharing

**Comment by bdw429s** [comment]
@computergeek1507 Thanks for the additional testing.

> this "[ inline-image ]" red line error

This looks to be an unsupported feature in our exporter.  Do you have a public URL where we can view the original Gitbook and a page number so I can see what should display there?  I'll create a new ticket to track adding that feature.

> this error too

I actually think that may be the same CMKY image format I put in a "fix" for.  Well, I wrapped the image resize code in a try/catch so images of that type just wouldn't be resized.  The look of that error seems that the underlyiing Apache library may have dumped the stack to the console despite the fact I caught the error, so there may not be anything I can do about the output on the screen, but likely there is no issue, it's just an unfortunate case of a chatty Java lib dumping crap to the screen when underlying errors happen.  (A [library upgrade in my underlying JVM language](https://luceeserver.atlassian.net/browse/LDEV-1388) will need to happen to support that file format)  I'm back home today from traveling so I'll look more closely at it.  The fact that the job logs on the screen show in green means it looks like everything was successful-- or at least there were no unhandled errors.  

Can you capture the full output of the command using the `--verbose` flag as that captures more details?
```
gitbook export --verbose
```

**Comment by computergeek1507** [comment]
https://manual.xlights.org/xlights/

**Comment by bdw429s** [comment]
@computergeek1507 I'm unable to reproduce the image exception, but as I said above, I think it's just a Java lib being chatty in your console.  

Here is the ticket for the inline-image.  I have it working, but need @scottsteinbeck to help me out a bit with the styles since gitbook has a line break before the first inline image and the exporter isn't doing that.

https://github.com/scottsteinbeck/commandbox-gitbook/issues/34

**Comment by bdw429s** [comment]
@computergeek1507 Inline image support has been added now via ticket #34 
```
update --system
```
