### ISSUE TITLE
Problem with code display

### ISSUE THREAD

**Issue by ycl6** [scottsteinbeck/commandbox-gitbook#40]
Hi,

I am trying to convert the exported json into html or pdf, however, I can't have the code block display properly. It seems the code block inside the json file is in **code-line** type instead of **code-tab** type.

I tried 3 examples: inline code, single-line code, multi-line code on https://app.gitbook.com/. From the exported content, I have below is a snippet of the json
```
{"kind":"block","type":"paragraph","key":"2","isVoid":false,"data":{},"nodes":[{"kind":"text","key":"1","ranges":[{"kind":"range","marks":[],"text":"Test "},{"kind":"range","marks":[{"kind":"mark","data":{},"type":"code"}],"text":"inline code"}]}]},
{"kind":"block","type":"code","key":"fc8203c8bc72456f922278611a2262e8","isVoid":false,"data":{"syntax":"text"},"nodes":[{"kind":"block","type":"code-line","key":"1a22f46d22ac4747aa8eac996ff4b107","isVoid":false,"data":{},"nodes":[{"kind":"text","key":"666f2e9503a74cd49d60da3c547f5538","ranges":[{"kind":"range","marks":[],"text":"Test single-line code"}]}]}]},
{"kind":"block","type":"code","key":"e6101c6267e64517ae65986bed256d76","isVoid":false,"data":{"syntax":"text"},"nodes":[{"kind":"block","type":"code-line","key":"2010b24590134d46a6103d855f6ec78d","isVoid":false,"data":{},"nodes":[{"kind":"text","key":"1cf78e6a104945e0908117d485d6ef9d","ranges":[{"kind":"range","marks":[],"text":"Test multiline code"}]}]},{"kind":"block","type":"code-line","key":"1ae86c66ed644dd99c9b55f4ea28f46e","isVoid":false,"data":{},"nodes":[{"kind":"text","key":"a1d8dfa76a92400ca7cc55c84c03ea11","ranges":[{"kind":"range","marks":[],"text":"Test line2"}]}]}]}
```

The converted HTML source code is as below:
```
<div class="document">
    <p>Test <span class="mark-code">inline code</span></p>
	<div class="code">Test single-line code</div>
	<div class="code">Test multiline code
Test line2
</div>
</div>
```
The resulting HTML looks like below where the inline code works, the other two were displayed as plain text lines:

Test `inline code`
Test single-line code
Test multiline code Test line2

**Comment by bdw429s** [comment]
Hi @ycl6 and thanks for the ticket.  I'm using Gitbook for several projects and the code blocks seem to be displaying ok.  Can you help provide us with a few things?

- The version of the module you're using (find out with the `list --system` command)
- A link to the online Gitbook version of your book
- A copy of the JSON export for us to test with
- A screenshot of one of the code blocks that aren't looking correct to you.

**Comment by bdw429s** [comment]
@ycl6 A quick update-- @scottsteinbeck thinks he may know what your issue is.  We'll push a new version of them module shortly for you to test.

**Comment by rambabuiitk** [comment]
@bdw429s Thanks, I have been having same from last 10 days. It used to work before. I noticed the same as @ycl6 mentioned when I compared..**code-line** vs **code-tab**

**Comment by ycl6** [comment]
@bdw429s @scottsteinbeck Thanks. I'll try the new version when it is ready.

**Comment by scottsteinbeck** [comment]
@rambabuiitk @ycl6 I have updated the styles and workflow for the code blocks. please update to the new version.

**Comment by rambabuiitk** [comment]
@scottsteinbeck Hitting with the below error...Do I need to set any env variable?

 × | Processing Export
   |--------------------------------
   | × | Render Book as HTML
   |   | > variable [MODULESETTINGS] doesn't exist
   |   |----------------------------------
   |   | √ | Build Table Of Contents
   |   | √ | Building Assets

ERROR (4.8.0+00059)

variable [MODULESETTINGS] doesn't exist

**Comment by scottsteinbeck** [comment]
Type "r" and hit enter to reload your commandbox console. it should work
after that.


Scott Steinbeck
scottsteinbeck@gmail.com
661-717-6486

[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
11/27/19,
08:56:00 AM

**Comment by rambabuiitk** [comment]
@scottsteinbeck Thanks for the quick fix...Its working great..

**Comment by bdw429s** [comment]
@rambabuiitk Thanks for confirming.  @ycl6 Please let us know how your testing goes.  You can update system modules like so:
```bash
update --system
```

**Comment by ycl6** [comment]
@bdw429s I tried v1.1.10, but encounter the below error. 
Where should I add the jvm.args or JAVA_OPTS? I tried a few variations, but none seems to work.

```
 × | Processing Export
   |--------------------------------
   | × | Render Book as HTML
   |   |----------------------------------
   |   | √ | Build Table Of Contents
   |   |   |--------------------------------------
   |   | √ | Building Assets
   |   |   |------------------------------
   |   | × | Render Pages
   |   |   | > Lucee was not able to load a Agent dynamically! You need to load one manually by adding the following to your JVM arguments [-javaagent:"/home/ycl6/.CommandBox/engine/cfml/cli/lucee-server/context/lucee-external-agent.jar"]
   |   |   |---------------------------                                                                                                   |   |   | NGS Analysis
   |   |   |---------------------------

ERROR (4.8.0+00059)
```

**Comment by bdw429s** [comment]
@ycl6 your issue is actually that you're using java 9+ and you need to use Java 8 for CommandBox 4.8.0. This is a known issue with the JVM language in tha version due to changes in how newer java versions load instrumentation.  The next version of CommandBox will support higher versions of java.  Depending on your OS, you can set Java 8 as your default JRE, or you can download the "JRE Included" version of CommandBox which simply contains a folder called "jre" that goes in the same folder as the `box` binary.

**Comment by ycl6** [comment]
@bdw429s Thanks, that instatly solved my problem.
I confirm the issue is resolved.

On a side note, the message towards the end of the stdout is always the opposite of what is produced, i.e. if I choose to output only PDF, the last message always says the HTML was produced, and vice versa.

```
CommandBox> gitbook export --showTOC --PDF --verbose codeHighlighlightTheme=perldoc pagetype=A4

   |   |   |---------------------------
   | √ | Building PDF
   |   |---------------------------
   |   | Writing PDF to /home/ycl6/gitbook/NGS-Analysis.pdf
   |   |---------------------------

Complete!

HTML written to /home/ycl6/gitbook/NGS-Analysis.html
```

**Comment by bdw429s** [comment]
@ycl6 Oops, good catch.  I had some sloppy copy and paste code there.  I have fixed those output messages in the latest version and I'm pleased to hear the export is working for you.
