### ISSUE TITLE
Add images for messages like green checkbox, etc

### ISSUE THREAD

**Issue by bdw429s** [scottsteinbeck/commandbox-gitbook#9]

**Comment by bdw429s** [comment]
![image](https://user-images.githubusercontent.com/584009/62582686-e76d6700-b872-11e9-82a4-5166924cffce.png)

![image](https://user-images.githubusercontent.com/584009/62582693-eccab180-b872-11e9-8130-83f4d35056c7.png)

**Comment by bdw429s** [comment]
![image](https://user-images.githubusercontent.com/584009/62582720-ffdd8180-b872-11e9-9e18-7b6567edbe89.png)

**Comment by scottsteinbeck** [comment]
added in images
